version: '3.9'
services:
  database-app:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data
  navisite-app:
    container_name: msadeqsirjani/navisite-app
    build: ./app/Navisite/.
    restart: always
    ports:
      - 5240:5240
      - 5241:5241
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5241
      - ASPNETCORE_URLS=http://+:5240
volumes:
  database:
    driver: local

  