version: '3.9'
services:
  navisite-database:
    container_name: navisite-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - database:/var/lib/postgresql/data
  navisite-app:
    container_name: navisite-app
    build: ./app/Navisite/.
    restart: always
    ports:
      - 5240:5240
      - 5241:5241
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5241
      - ASPNETCORE_URLS=http://+:5240
  navisite-reverse-proxy:
    container_name: navisite-reverse-proxy
    build: ./nginx/.
    restart: always
    ports:
      - 81:80
    depends_on:
      - navisite-app
volumes:
  database:
    driver: local

  