version: '3.9'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=strip_example
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    container_name: app
    build: ./app/Navisite/.
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    ports:
      - 5240:5240
      - 5241:5241
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5241
      - ASPNETCORE_URLS=http://+:5240
  reverse-proxy:
    container_name: reverse-proxy
    build: ./nginx/.
    restart: always
    deploy:
        resources:
            limits:
              cpus: '0.50'
              memory: 512M
            reservations:
              cpus: '0.25'
              memory: 128M
    ports:
      - 81:80
    depends_on:
      - app 
volumes:
  pg_data:
    driver: local